apiVersion: v1
kind: Pod
metadata:
  name: test-demo
spec:
  containers:
    - name: test-demo-container
      image: demo:1.0
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config #ConfigMap数据存放位置      
      env:
      # 定义环境变量
        - name: PORT
          valueFrom:
            configMapKeyRef:
              # ConfigMap名称
              name: demo-config
              # 引用的key
              key: demo.port
  volumes:
    - name: config-volume
      configMap:
        # ConfigMap名称
        name: demo-config
        name: example-demo-file-config
        items:
        - key: demo-config.json
          path: config.json                      
  restartPolicy: Never