apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: istio-system
spec:
  ports:
  - name: redis-port
    protocol: TCP
    targetPort: 6379
    port: 6379
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: istio-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:latest
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379 