- name: elasticsearch
  hosts: elastic
  roles:
    - role: elastic.elasticsearch
  vars:
    # 堆内存容量
    es_heap_size: "1g"
    es_version: 6.8.4
    es_data_dirs:
      - /data/elasticsearch/data
    es_log_dir: /data/elasticsearch/log
    es_max_open_files: 65536 # 文件描述符数量
    # 使用rpm包安装
    es_use_repository: false
    es_custom_package_url: "https://mirrors.huaweicloud.com/elasticsearch/6.8.4/elasticsearch-6.8.4.rpm"
    es_api_basic_auth_username: admin
    es_api_basic_auth_password: admin
    es_config:
      cluster.name: "log-cluster" #集群名称
      # 服务发现和集群形成设置
      #cluster.initial_master_nodes: "log-cluster02" # 初始主节点
      #discovery.seed_hosts: "log-cluster:9300" # 服务发现种子主机
      node.name: log-node-01
      http.host: 0.0.0.0
      http.port: 9200
      node.data: true
      node.master: true
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment
    es_users:
      file:
        xxx:
          password: xxx
          roles:
            - admin
        testUser:
          password: testUser!
          roles:
            - power_user
            - user
    es_roles:
      file:
        admin:
          cluster:
            - all
          indices:
            - names: '*'
              privileges:
                - all
        power_user:
          cluster:
            - monitor
          indices:
            - names: '*'
              privileges:
                - all
        user:
          indices:
            - names: '*'
              privileges:
                - read
